### ISSUE TITLE
Copy button is off / doesn't work on installation page

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#1120] opened 2023-09-12 09:09 UTC
https://duckdb.org/docs/installation/

**Comment by Mause** [comment] 2023-09-12 09:12
Duplicate of https://github.com/duckdb/duckdb-web/issues/931

**Closed by Mause** 2023-09-12 09:12 UTC
Labels: design

**Comment by szarnyasg** [comment] 2023-09-12 09:27
Thanks, tagged the other issue as `design`.
